# Generated by Django 5.1.4 on 2025-04-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_placement_', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('question_text', models.TextField()),
                ('mark', models.PositiveIntegerField(default=1)),
                ('option_A', models.TextField()),
                ('option_B', models.TextField()),
                ('option_C', models.TextField()),
                ('option_D', models.TextField()),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', help_text='Key of the correct option for MCQs.', max_length=1)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_code', models.CharField(max_length=10, unique=True)),
                ('paper_title', models.CharField(max_length=255)),
                ('paper_description', models.TextField(blank=True, null=True)),
                ('time_limit', models.PositiveIntegerField(help_text='Time limit in minutes')),
                ('no_of_qs', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('is_practice_paper', models.BooleanField(default=True)),
                ('is_assessment_paper', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Question Paper',
                'verbose_name_plural': 'Question Papers',
            },
        ),
        migrations.AlterModelOptions(
            name='studentresults',
            options={'verbose_name': 'Student Result', 'verbose_name_plural': 'Student Results'},
        ),
        migrations.RemoveIndex(
            model_name='studentresults',
            name='Dplacement__date_of_c07e18_idx',
        ),
        migrations.AlterUniqueTogether(
            name='studentresults',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentresults',
            name='date_of_exam',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentresults',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentresults',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Malpractice', 'Malpractice')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentresults',
            name='test_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentresults',
            name='test_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentresults',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='_placement_.questionpaper'),
        ),
        migrations.RemoveField(
            model_name='studentresults',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='studentresults',
            name='obtained_marks',
        ),
    ]
