# Generated by Django 5.2 on 2025-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_placement_', '0003_batch_material_question_questionpaper_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_platforms',
        ),
        migrations.AddField(
            model_name='user',
            name='codechef_link',
            field=models.URLField(blank=True, null=True, verbose_name='CodeChef Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='hackerrank_link',
            field=models.URLField(blank=True, null=True, verbose_name='HackerRank Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='leetcode_link',
            field=models.URLField(blank=True, null=True, verbose_name='LeetCode Profile'),
        ),
    ]
