# Generated by Django 5.1.4 on 2025-04-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_placement_', '0003_mistakenquestion_student_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codechef_link',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='CodeChef Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hackerrank_link',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='HackerRank Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leetcode_link',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='LeetCode Profile'),
        ),
    ]
