# Generated by Django 5.1.4 on 2025-04-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_placement_', '0004_batch_section_delete_class_alter_user_options_and_more'),
    ]

    operations = [
    ]
