# Generated by Django 5.1.4 on 2025-04-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_placement_', '0004_alter_user_codechef_link_alter_user_hackerrank_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codechef_link',
        ),
        migrations.AddField(
            model_name='user',
            name='dsa_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dsa_problem_solved_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gfg_link',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='GeeksforGeeks Profile'),
        ),
    ]
