# Generated by Django 5.2 on 2025-04-18 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_placement_', '0004_remove_user_code_platforms_user_codechef_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], default=2029, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
